### ISSUE TITLE
Upgrade spring-cloud-stream-dependencies to 3.1.0.BUILD-SNAPSHOT?

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-stream-starters#103]
I saw that the current version of spring-cloud-stream-dependencies is currently at [3.0.4.BUILD-SNAPSHOT](https://github.com/spring-cloud/spring-cloud-stream-starters/blob/master/spring-cloud-stream-dependencies/pom.xml#L18). Can we update this to `3.1.0.BUILD-SNAPSHOT`?

Right now `3.0.4.BUILD-SNAPSHOT` is incompatible with the latest milestone release of Spring integration (version `5.3.0.M3`). One incompatibility is that in the latest Spring Integration, `AbstractSubscribableChannel` has a method that was renamed from `getChannelInterceptors` to `getInterceptors`. The update from spring-cloud-stream to change to this API was made in [`3.1.0.BUILD-SNAPSHOT` here](https://github.com/spring-cloud/spring-cloud-stream/commit/8b3b0815a47dcaae54bb1128f782b54408aa7e9b), but the fix does not exist in `3.0.4.BUILD-SNAPSHOT`.

**Comment by olegz** [comment]
Yes, Ivyland.B-S is 3.1.0. - https://github.com/spring-cloud/spring-cloud-stream-starters/blob/master/pom.xml

**Comment by dzou** [comment]
I see, but [the pom for this repo](https://github.com/spring-cloud/spring-cloud-stream-starters/blob/master/spring-cloud-stream-dependencies/pom.xml) must also be updated right? I.e. the version numbers `spring-cloud-stream.version` should be bumped to 3.1.0.BUILD-SNAPSHOT?

Right now when we depend on Ivyland.B-S we are still getting 3.0.4.B-S.

**Comment by dzou** [comment]
To just clarify what I am saying -

When we add this to our pom:

```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-stream-dependencies</artifactId>
      <version>Ivyland.BUILD-SNAPSHOT</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

We get spring-cloud-stream version `3.0.4.BUILD-SNAPSHOT` for our project. But I was expecting to get the very latest version `3.1.0.BUILD-SNAPSHOT` instead; 3.1.0.BUILD-SNAPSHOT has those fixes that makes it compatible with the latest spring integration. Do you guys agree with this assessment?

**Comment by olegz** [comment]
That's because there is an issue with snapshot publishing.
Let me get back to you tomorrow, We need to fix it on our end

**Comment by dzou** [comment]
Ok! Thank you for your help on this!

**Comment by dzou** [comment]
Fixed.
