### ISSUE TITLE
Remove docbook from asciidoctor integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-starters#12]

**Comment by ericbottard** [comment]
I assume this is no longer relevant @sabbyanandan ?

**Comment by sabbyanandan** [comment]
Yes and I need to move all the issues from this repo to [spring-cloud-stream-app-starters](https://github.com/spring-cloud-stream-app-starters/app-starters-release), too. This repo is no longer tracked.

**Comment by sabbyanandan** [comment]
Oops; ignore the previous comment about the "move" - I confused this with "stream **app** starters" repo. This repo is very much tracked! 😄
