### ISSUE TITLE
Upgrade Spring Boot to 2.0 SNAPSHOTs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-starters#24]
As a developer, I'd like to upgrade Spring Boot version to 2.0.0.BUILD-SNAPSHOT.

**Acceptance:**
- Document general findings
- Capture breaking changes
- Prepare for SCSt 2.0 branch and CI pipeline

**Comment by mbogoevici** [comment]
This is complete now after creating `2.0.x` branches in Core and binders and the `Elmhurst.x` branch.
