### ISSUE TITLE
Prepare for Elmhurst release

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-starters#26]

**Comment by mbogoevici** [comment]
The `Elmhurst.x` branch has been created, as well as the CI plans - 

https://jenkins.spring.io/job/spring-cloud-stream-Elmhurst-x-builds/

https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/spring-cloud-stream-dependencies/Elmhurst.BUILD-SNAPSHOT/
