### ISSUE TITLE
Using AWS SQS or Kinesis for exchanging metrics data between Hystrix.stream and Turbine

### ISSUE THREAD

**Issue by hbagchi** [spring-cloud/spring-cloud-stream-starters#31]
I am looking for a **Binder** implementation for **AWS SQS** or **Kinesis**. I did find a Kinesis Binder. I am yet to use it though. I am assuming I can use it as a drop-in replacement for a Rabbit binder and push hystrix.stream data to Kinesis. What I am not getting is how to use it with Turbine to pull data from Kinesis? 
Is there any examples that I can use?

**Comment by sabbyanandan** [comment]
Hi, @hbagchi. Yes, we have a kinesis-binder under incubation and we have plans to release the binder implementation. To integrate with Turbine, all you'd probably need is to swap `spring-cloud-starter-stream-rabbit` with `spring-cloud-starter-stream-aws-kinesis` [dependency](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_turbine_stream). You can try with SNAPSHOTs if you'd like, but it hasn't been vetted out by the team yet. 

For issues specific fo kinesis-binder, please use its [repo](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues) and for hysterix/turbine, you can use their respective backlogs.
