### ISSUE TITLE
Snapshot BOM has M1 dependencies

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream-starters#4]
What's the point of Brooklyn.BUILD-SNAPSHOT if all the stream dependencies are fixed to M1? I want the latest snapshots.

**Comment by mbogoevici** [comment]
They've been set to M1 during the release. Will be set back to snapshots afterwards.

**Comment by mbogoevici** [comment]
As a side note:  the point of Brooklyn.XYZ is to manage the versions. The fact that they're milestones doesn't render the BOM pointless, as suggested.

I do agree that in a SNAPSHOT, dependencies should be SNAPSHOTS, though, hence they need to be reset.
