### ISSUE TITLE
Modular docs from the release-train projects don't end up in the reference guide

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-starters#42]
As a developer, I'd like to make sure binder specific modular doc-fragments end up in the aggregated reference guide. 

Notes:
It appears `spring-cloud-stream-aggregate.adoc` is not including the newly added sub-sections. (e.g., `partitions.adoc`). 

Perhaps it'd be better to add a binder-level "aggregate doc" (that includes dlq and partitions for now; others in future) and then include the new doc in the aggregated reference guide (i.e., `spring-cloud-stream-aggregate.adoc`). That way we won't have to add and maintain new inclusions for every release explicitly. It is easy to miss if it is not automated.

**Comment by sobychacko** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-stream-starters/commit/3114fc06381076d4e902478479cbab9e2226bd21.
