### ISSUE TITLE
I think Amazon MQ might be a very good addition for the binders

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-stream-starters#45]
Amazon MQ offers managed AMPQ messaging brokers so adding a binder for this would be very beneficial to many.

**Comment by artembilan** [comment]
Looks like we don’t need to think if it is Amazon MQ or anything else. In the end it is just Apache  Active MQ: https://aws.amazon.com/amazon-mq/.

So, sounds like this is a request for the existing JMS Binder project: https://github.com/spring-cloud/spring-cloud-stream-binder-jms. I see there is already something about Active MQ.

WDYT, @mv78 ?
