### ISSUE TITLE
Fishtown RC1 announcement: release notes link broken

### ISSUE THREAD

**Issue by yonigibbs** [spring-cloud/spring-cloud-stream-starters#53]
@olegz: I just read your announcement about the Fishtown RC1 release [here](https://spring.io/blog/2018/10/30/spring-cloud-stream-fishtown-rc1-2-1-0-rc1-release-announcement).  The link to the release notes appears to be broken: https://github.com/spring-cloud/spring-cloud-stream-starters/releases/tag/vFishtown.RC1.

Am logging it here as it seems to link to this repository.  Apologies if it's not the right place to log it.

**Comment by olegz** [comment]
Where did you get that link?

**Comment by yonigibbs** [comment]
On the blog announcement: https://spring.io/blog/2018/10/30/spring-boot-2-1-0

**Comment by olegz** [comment]
Ok, will fix, thx

**Comment by yonigibbs** [comment]
You're welcome.

**Comment by olegz** [comment]
Removed that sentence all together since relevant information appears throughout he blog anyway.
Thanks again for pointing this out
