### ISSUE TITLE
Add binder implementation for AWS Kinesis

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-starters#9]
_From @atdi on March 25, 2016 21:14_

As long kafka is not available as a managed service on AWS this will be nice to have.

_Copied from original issue: spring-cloud/spring-cloud-stream#453_

**Comment by sabbyanandan** [comment]
_From @artembilan on March 25, 2016 21:17_

:+1: 
Fully relates to the https://github.com/spring-projects/spring-integration-aws/issues/22

**Comment by sabbyanandan** [comment]
_From @atdi on March 25, 2016 21:31_

Where this should be implemented: here or in spring-integration-aws? The starter definitely should be here.

**Comment by sabbyanandan** [comment]
_From @mbogoevici on March 26, 2016 15:27_

Hi @atdi,

Opening the issue here was the right thing to do :). In terms of where this will eventually live: we encourage the development of binders in separate repositories (e.g. https://github.com/spring-cloud/spring-cloud-stream-binder-redis and https://github.com/spring-cloud/spring-cloud-stream-binder-gemfire) for ease of management and decoupling their release cycle (at least until they become stable enough). Until we get started on it though, it's good to have the requirement in a visible place (also see https://github.com/spring-cloud/spring-cloud-stream/issues/135 for example).

What @artembilan meant was that our binders are based on SI components, so the development of the Kinesis binder will also entail creating the associated SI inbound/outbound adapters for Kinesis - just as we do with Kafka for instance. Thus, an entire range of associated Spring projects can benefit from the progress.

Thanks for opening the issue and keep watching this space (or feel free to contribute if you'd like to hack on it for a bit, we are always welcoming that!). 

Cheers,
Marius

**Comment by oatesp** [comment]
Has anyone started work on this binder implementation? I don't see a repository for it. 

I'd really like to progress this so I can make use of kinesis in place of kafka, I'm willing to take a look, does a repository need setting up first or should I just start hacking on something?

Thanks,
Peter.

**Comment by artembilan** [comment]
@oatesp ,

Thank you very much for the willing to start the work on the matter!

I'm having plans to step into this subject somewhere in the next month, when we will finish the current Spring Integration Milestone. But anyway you can start the hacking locally as you wish. When there will be something ready, we will come back to you with review on your request.

You need [Spring Integration AWS](https://github.com/spring-projects/spring-integration-aws) as a channel adapters foundation.
And [Spring Cloud Stream Binder for Apache Kafka](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka) as a sample how to go with `AbstractBinder` and `ProvisioningProvider`.

We will create a repo as it will be needed.

Feel free to come back to us here with any questions on the matter!

**Comment by vishalmanohar** [comment]
Hi, is there any timeline when support for Kinesis will be ready. Will be happy to help test.

**Comment by almostsultry** [comment]
👍 I really need this feature.

**Comment by artembilan** [comment]
Well, thank you guys, for the interest to this!

Very appreciate!

I will be able to come back to this feature in the next month with the hope to have something working in the end of June.

I won't mind if our team will share the vision as well.

/CC @sabbyanandan

**Comment by oatesp** [comment]
Hi,

I've put together a basic binder implementation for Kinesis, based on the Kafka binder. I've hooked this up to a prototype application which is successfully placing messages on a kinesis stream. 

I'm having trouble consuming the messages however, unlike with kafka the kinesis implementation does not appear to read messages from the stream when it starts up, also when I send a message the kinesis-consumer thread exits with an error 
`Exception in thread "-kinesis-consumer-1" org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: [{SequenceNumber: 49573507241350746661810493410484325756611592007853277186,ApproximateArrivalTimestamp: Wed May 24 09:19:18 BST 2017,Data: java.nio.HeapByteBuffer[pos=0 lim=141 cap=141],PartitionKey: name}]; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
` 

I expect I've just missed something with the implementation. 

I'm happy to share the code I have if anyone wants to take a look with me. 


Thanks, 
Peter.

**Comment by artembilan** [comment]
@oatesp ,

I want.

That's nice to hear that there is someone interested and have a chance to go ahead.

@sabbyanandan , @mbogoevici , please, create a `spring-cloud-stream-binder-aws-kinesis` repo and we'll see what to do with @oatesp 's code.

Thank you @oatesp for the effort!

**Comment by sabbyanandan** [comment]
@oatesp Glad to hear that you've started implementing it!

As an update, we would like to support this binder implementation; however, we have competing priorities in existing binders and as well in other strategic areas within SCSt/SCDF ecosystem. Given the enormous interests in this subject, as @artembilan recommends, we will create the repo and start making progress via PRs. 

Once we have a rough cut on the implementation, it'd be great to have some validation on use-cases and feedback. Thanks everyone for the continued support.

**Comment by oatesp** [comment]
Thanks guys, I'll make a PR against that repo shortly.

**Comment by oatesp** [comment]
I've tried to push the code to create the pull request but am getting an error, do I need some permission to push a branch?

Thanks,
Peter.

**Comment by mbogoevici** [comment]
@oatesp Please fork the repository and make the PR from your fork - we follow the same procedure ourselves.

**Comment by behrangs-sportsbet** [comment]
Hi all,

Is this merged to `Elmhurst`? I can't see any mention of it in the [docs](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.M3/reference/htmlsingle/).

**Comment by artembilan** [comment]
That hasn't been merged yet.
We even haven't migrated it into `Elmhurst`.

I'm going to look into the Spring Cloud `2.0` base line for AWS Kinesis Binder after SprngOne, the next week.

**Comment by srinivas110** [comment]
I have observed consumer is stopped listening the messages after some time . I am using KinesisMessageChannelBinder.createConsumerEndpoint method  for creating consumer for stream.
consumer is listening the messages . suddenly it got stopped did not find out the reason . went through KinesisMessageDrivenChannelAdapter class has all the logic for consumer. really appreciate for your suggestions

**Comment by artembilan** [comment]
@srinivas110 ,

This is wrong place for such a comment.

Please, proceed to the appropriate project https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues and share there in new issue as much info as possible. Would be even better to have a simple application for reproduction on our side. Your current comment doesn't bring too much technical arguments.

Thanks
